#!/bin/bash

# mjm : a minimal job manager written in bash (yes bash)
#
#   (c) Romain Mueller, name dot surname at gmail dot com
#
# This file simply dispatches the commands as follows:
#
#   mjm command arguments
#
# gives
#
#   /path/to/mjm/command.sh arguments
#

if [ -z "$1" ]; then
  echo "Please provide a command. Type 'help' for help."
  exit 1
fi

# get env vars
source ~/.config/mjm/mjm.cfg

# run the command
"$MJM_PATH"/cmds/"${1}".sh "${@:2}"
